const fs = require('fs');
const path = require('path');

async function generateReport() {
    const ledgerPath = path.join(process.cwd(), 'integrity_ledger.json');
    if (!fs.existsSync(ledgerPath)) {
        console.error('No integrity ledger found.');
        return;
    }

    const ledgerData = JSON.parse(fs.readFileSync(ledgerPath, 'utf8'));
    const history = ledgerData.history || [];
    const last7Days = Date.now() - (7 * 24 * 60 * 60 * 1000);
    const weeklyEvents = history.filter(e => new Date(e.timestamp).getTime() > last7Days);

    const totalPRs = weeklyEvents.length;
    const preventedIncidents = weeklyEvents.filter(e => e.score < 100 || (e.metrics && e.metrics.security_findings > 0)).length;
    const avgScore = totalPRs > 0 ? weeklyEvents.reduce((acc, e) => acc + (e.score || 100), 0) / totalPRs : 100;

    const report = `# [XORAS] Weekly Integrity Report
**Pilot Week:** 1
**Date:** ${new Date().toLocaleDateString()} - ${new Date(last7Days).toLocaleDateString()}
**Status:** ADVISORY MODE

---

## 🛡️ Executive Summary
This week, XORAS provided release visibility for **${totalPRs}** pull requests. 

* **Prevented Incidents:** ${preventedIncidents}
* **Average Integrity Score:** ${Math.round(avgScore)}/100
* **Deployment Drift Detected:** ${preventedIncidents > 0 ? 'HIGH' : 'LOW'}

---

## 📈 Integrity Trends
| Category | Status | Observation |
| --- | --- | --- |
| **Security** | ${weeklyEvents.some(e => e.metrics.security_findings > 0) ? '⚠️ DRIFT' : '✅ HEALTHY'} | ${weeklyEvents.reduce((acc, e) => acc + e.metrics.security_findings, 0)} exposed secrets prevented. |
| **Performance** | ${weeklyEvents.some(e => e.latencyDrift > 15) ? '⚠️ DRIFT' : '✅ HEALTHY'} | Highest latency regression: ${Math.max(...weeklyEvents.map(e => Math.round(e.latencyDrift)) || [0])}% |
| **Architecture** | ✅ HEALTHY | No dependency bloat detected. |

---

## 🚨 Top Prevented Risks
${weeklyEvents.filter(e => e.score < 100).slice(0, 3).map(e => `- **PR #${e.pr_number || 'N/A'}**: ${e.violations.join(', ')}`).join('\n') || '- No critical risks detected this week.'}

---

## 🛠️ Next Steps
1. **Calibrate thresholds** for performance drift (current baseline: 15%).
2. **Review remediation paths** for frequent security warnings.
3. **Weekly Pilot Sync**: Friday at 10:00 AM.

---
*Generated by XORAS Intelligence Engine*
`;

    fs.writeFileSync('WEEKLY_REPORT.md', report);
    console.log('WEEKLY_REPORT.md generated successfully.');
}

generateReport();
