const fs = require('fs');
const path = require('path');
const preemptiveGuard = require('./preemptive_guard');

/**
 * XORAS Intelligence Core Orchestrator
 * Finality Standard: v2026.1
 */

class IntelligenceCore {
    constructor() {
        this.projectRoot = path.resolve(__dirname, '..');
        this.auditLogPath = path.join(this.projectRoot, 'intelligence_core/AUDIT_FINALITY.md');
    }

    /**
     * Executes a full institutional audit and generates the Finality Report.
     */
    async executeInstitutionalAudit() {
        console.log("🏛️ Initiating Institutional Audit Finality...");
        
        const workflowDir = path.join(this.projectRoot, '.github/workflows');
        const report = preemptiveGuard.auditWorkflows(workflowDir);

        this.generateStructureReport(report);
        return report;
    }

    /**
     * Generates a persistent, high-fidelity markdown report of all structural risks.
     * @param {Object} report 
     */
    generateStructureReport(report) {
        let md = `# XORAS Institutional Audit Finality\n\n`;
        md += `**Timestamp**: ${report.timestamp}\n`;
        md += `**Status**: ${report.status === 'CRITICAL' ? '⚠️ CRITICAL RISKS DETECTED' : '✅ SYSTEM SECURE'}\n\n`;
        
        md += `## 🔍 Structural Analysis Summary\n${report.summary}\n\n`;

        if (report.vulnerabilities.length > 0) {
            md += `## 🛠️ Required Solutions (Red X Resolution)\n\n`;
            report.vulnerabilities.forEach((v, i) => {
                md += `### [${i + 1}] ${v.type} in \`${v.file}\`\n`;
                md += `> **Risk**: ${v.message}\n\n`;
                md += `**Literal Solution**:\n- ${v.solution}\n\n`;
                md += `---\n\n`;
            });
        } else {
            md += `✅ No structural vulnerabilities identified in the current release candidate.\n`;
        }

        md += `\n*This report was generated by the XORAS Strategic Apex Tier.*`;

        fs.writeFileSync(this.auditLogPath, md);
        console.log(`✅ AUDIT_FINALITY.md generated at ${this.auditLogPath}`);
    }
}

const core = new IntelligenceCore();

// Execute immediately to provide the user with the "Big Brain" output
core.executeInstitutionalAudit();

module.exports = core;
