const fs = require('fs');
const path = require('path');
const preemptiveGuard = require('./preemptive_guard');

/**
 * XORAS Repository Integrity Orchestrator
 * Purpose: Technical verification of workflow security and configuration grounding.
 */

class AuditOrchestrator {
    constructor() {
        this.projectRoot = path.resolve(__dirname, '..');
        this.reportPath = path.join(this.projectRoot, 'intelligence_core/audit_report.md');
    }

    /**
     * Executes technical audit of GitHub workflows and repository structure.
     */
    async executeAudit() {
        console.log("Starting Technical Audit of Repository Integrity...");
        
        const workflowDir = path.join(this.projectRoot, '.github/workflows');
        const report = preemptiveGuard.auditWorkflows(workflowDir);

        this.generateTechnicalReport(report);
        return report;
    }

    /**
     * Generates an objective markdown report of identified security risks.
     * @param {Object} report 
     */
    generateTechnicalReport(report) {
        let md = `# XORAS Repository Integrity Audit Report\n\n`;
        md += `**Timestamp**: ${report.timestamp}\n`;
        md += `**Status**: ${report.status === 'CRITICAL' ? 'SECURITY_ALERT' : 'STABLE'}\n\n`;
        
        md += `## Technical Summary\n${report.summary}\n\n`;

        if (report.vulnerabilities.length > 0) {
            md += `## Identified Risks & Remediation\n\n`;
            report.vulnerabilities.forEach((v, i) => {
                md += `### [${i + 1}] ${v.type} in \`${v.file}\`\n`;
                md += `- **Technical Detail**: ${v.message}\n`;
                md += `- **Remediation**: ${v.solution}\n\n`;
                md += `---\n\n`;
            });
        } else {
            md += `No security or structural issues identified in the current audit.\n`;
        }

        md += `\n*Report generated by XORAS Audit Orchestrator.*`;

        fs.writeFileSync(this.reportPath, md);
        console.log(`Audit report generated at ${this.reportPath}`);
    }
}

const orchestrator = new AuditOrchestrator();
orchestrator.executeAudit();

module.exports = orchestrator;
