const fs = require('fs');
const path = require('path');
const preemptiveGuard = require('./preemptive_guard');

/**
 * XORAS Scoped-Detection Orchestrator
 * Standard: Deterministic Bounded Audit (v1.0)
 */

class AuditOrchestrator {
    constructor() {
        this.projectRoot = path.resolve(__dirname, '..');
        this.reportPath = path.join(this.projectRoot, 'intelligence_core/audit_report.md');
    }

    /**
     * Executes deterministic audit of repository workflows and configurations.
     */
    async executeAudit() {
        console.log("Starting Deterministic Audit (Bounded Scope)...");
        
        const workflowDir = path.join(this.projectRoot, '.github/workflows');
        const report = preemptiveGuard.auditWorkflows(workflowDir);

        this.generateTechnicalReport(report);
        return report;
    }

    /**
     * Generates a literal, technical report of identified structural risks.
     * @param {Object} report 
     */
    generateTechnicalReport(report) {
        let md = `# XORAS Repository Integrity Audit Report\n\n`;
        md += `**Timestamp**: ${report.timestamp}\n`;
        md += `**Scope**: Bounded Deterministic (v1.0)\n`;
        md += `**Status**: ${report.status === 'CRITICAL' ? '⚠️ SECURITY_ALERT' : '✅ STABLE'}\n\n`;
        
        md += `## Technical Summary\n${report.summary}\n\n`;

        if (report.vulnerabilities.length > 0) {
            md += `## Identified Risks & Remediation\n\n`;
            report.vulnerabilities.forEach((v, i) => {
                md += `### [${i + 1}] ${v.type} in \`${v.file}\`\n`;
                md += `- **Technical Detail**: ${v.message}\n`;
                md += `- **Remediation**: ${v.solution}\n\n`;
                md += `---\n\n`;
            });
        } else {
            md += `No security or structural issues identified within the defined deterministic scope.\n`;
        }

        md += `\n*This audit operates under a Transparent Fault Baseline. Report generated by XORAS.*`;

        fs.writeFileSync(this.reportPath, md);
        console.log(`Deterministic report generated at ${this.reportPath}`);
    }
}

const orchestrator = new AuditOrchestrator();
orchestrator.executeAudit();

module.exports = orchestrator;
